name: Process Images and Generate Footprints JSON

on:
  push:
    paths:
      - 'source/images/Footprint/**'  # 图片目录
  workflow_dispatch:  # 允许手动触发

jobs:
  extract-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          token: $GH_TOKEN   # 使用 PAT
          cache: 'npm' # 启用缓存加速安装

      - name: Debug - list files
        run: |
          pwd
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install exifr

      - name: Run metadata extraction
        run: node scripts/extract-image-metadata.js

      - name: Commit and push changes
        env:
          GIT_NAME: ${{ secrets.GIT_NAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          git config --global user.name $GIT_NAME
          git config --global user.email $GIT_EMAIL
          git add source/data/footprints.json
          git diff --staged --quiet || git commit -m "chore: auto-update footprints data from images"
          git push